/// This file can generate README.md by `typlite README.typ`

#let forest = green.darken(20%)
#let is-markdown = sys.inputs.at("x-target", default: "pdf") == "md"
#show "github.com": text.with(forest)
#show "codeberg.org": text.with(forest)
#show "gistd.myriad-dreamin.com": text.with(eastern)
#show "any-gistd.myriad-dreamin.com": text.with(red)
#show "@any": text.with(red)
#show link: text.with(blue)
#show link: underline

#let verbatim(body) = {
  show raw.where(lang: "verbatim"): it => html.elem("m1verbatim", attrs: (src: it.text))
  body
}

#if is-markdown {
  verbatim[
    ```verbatim
    <!-- This file is generated by `typlite README.typ` -->
    # Gistd
    ```
  ]
} else {
  align(center, text(size: 28pt)[Gistd])
}

Instantly share #link("https://typst.app")[typst] documents on git and other network storage.

= Loading a document on GitHub

Assuming that you have a GitHub link, for example:

```
https://github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

Simply replace the `github.com` with `gistd.myriad-dreamin.com`:

```
https://gistd.myriad-dreamin.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

Example Documents:

- https://gistd.myriad-dreamin.com/johanvx/typst-undergradmath/blob/main/undergradmath.typ
- https://gistd.myriad-dreamin.com/Jollywatt/typst-fletcher/blob/main/docs/manual.typ
- https://gistd.myriad-dreamin.com/typst/templates/blob/main/charged-ieee/template/main.typ

= Loading a single-file document by arbitrary links

Assuming that you have arbitrary link, for example:

```
https://github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

Put `any-gistd.myriad-dreamin.com` before the link:

```
https://any-gistd.myriad-dreamin.com/github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

If a domain is specially identified, gistd will use corresponding approach to serve the document.
- `github.com`: git protocol.
- `codeberg.org`: git protocol.

Note: gistd won't load other files on the specified domain if it cannot identifies the domain, i.e. the typst document cannot load other resources relative to the domain.

`any-gistd.myriad-dreamin.com` is alias for `gistd.myriad-dreamin.com/@any`.

Example Documents:

- https://any-gistd.myriad-dreamin.com/github.com/Myriad-Dreamin/gistd/raw/main/README.typ
- https://gistd.myriad-dreamin.com/@any/github.com/Myriad-Dreamin/gistd/raw/main/README.typ

= Loading a document without cors proxy

By default, gistd uses a trusted cors proxy to load documents. This is because GitHub and Forgejo doesn't allow gistd to load documents. See #link("https://isomorphic-git.org/docs/en/quickstart")[isomorphic-git: Quickstart] for more details.

However, you may want to load a document without cors proxy. You can do this by adding `g-cors=false` to the query string.

For example, to load a document at `http://localhost:11449/main.typ`:

- https://gistd.myriad-dreamin.com/@http/localhost:11449/main.typ?g-cors=false

= Loading a document with HTTP protocol

For example, to load a document at `http://localhost:11449/main.typ`:

- https://gistd.myriad-dreamin.com/@http/localhost:11449/main.typ?g-cors=false


#if is-markdown [
  == Development

  Install dependencies:

  ```
  pnpm install
  ```

  Develop locally:

  ```
  pnpm dev
  ```

  Build:

  ```
  pnpm build
  ```
]
